### ISSUE TITLE
エントリーポイントのバリデーション

### ISSUE THREAD

**Issue by mazrean** [traPtitech/trap-collection-server#1016]
エントリーポイントの設定ミスで正常に起動しないことがかなり多いので、バリデーションをかけたい。
単純にzip内に指定のパスが存在するか確認するだけでだいぶミスが減りそうな気がしている。
実行ファイルの形式のチェックとかまでできるとほぼ動かないことはなくなる気はする。

**Comment by mazrean** [comment]
たぶん展開しなくてもパスの一覧までは取り出せる気がするけど、仮に展開する場合はメモリに乗せないように注意する必要がある。

**Comment by ikura-hamu** [comment]
標準の[archive/zip](https://pkg.go.dev/archive/zip)使えば展開せずにできそうだと思ったけど、`io.ReaderAt`が必要そうでできないかも

**Comment by ikura-hamu** [comment]
1回ローカルに保存するしかない？
