### ISSUE TITLE
GetGameInfosByLauncherVersionの分割

### ISSUE THREAD

**Issue by mazrean** [traPtitech/trap-collection-server#244]
GetGameInfosByLauncherVersionが、ゲームの取得、ゲームの最新紹介画像・動画取得、ゲームの最新バージョンの取得、ゲームバージョンのファイル・URL取得、とやっていることが多い。
うまく分割して可読性を上げるのをしたい。

**Comment by ikura-hamu** [comment]
GetGameInfosByLauncherVersionはv2移行によって使われなくなった
