### ISSUE TITLE
mp4の音量を調整する

### ISSUE THREAD

**Issue by JichouP** [traPtitech/trap-collection-server#254]
https://qiita.com/habhit/items/0249b9dc5550ad00609e

**Comment by JichouP** [comment]
### -30 LUFS

`ffmpeg -i Tutorial2.mp4 -af "loudnorm=I=-30:TP=-3:LRA=4:print_format=summary,channelmap=channel_layout=stereo,aresample=48000:resampler=soxr" -c:v copy -c:a aac 30.mp4`

```plaintext
Input Integrated:    -13.9 LUFS
Input True Peak:      +0.6 dBTP
Input LRA:            10.0 LU
Input Threshold:     -24.1 LUFS

Output Integrated:   -29.9 LUFS
Output True Peak:    -13.8 dBTP
Output LRA:            4.5 LU
Output Threshold:    -40.0 LUFS
```

### -40 LUFS

`ffmpeg -i Tutorial2.mp4 -af "loudnorm=I=-40:TP=-3:LRA=4:print_format=summary,channelmap=channel_layout=stereo,aresample=48000:resampler=soxr" -c:v copy -c:a aac 40.mp4`

```plaintext
Input Integrated:    -13.9 LUFS
Input True Peak:      +0.6 dBTP
Input LRA:            10.0 LU
Input Threshold:     -24.1 LUFS

Output Integrated:   -39.9 LUFS
Output True Peak:    -23.8 dBTP
Output LRA:            4.5 LU
Output Threshold:    -50.0 LUFS
```

**Comment by mazrean** [comment]
サーバーではやらないことになった
